#!/usr/bin/env python


import argparse

import qrandom


def get_ints():
    return qrandom._api.fetch()


def get_hex():
    return qrandom._api.make_request().json()["data"]


def main():
    parser = argparse.ArgumentParser(
        description="Get samples for testing.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--type",
        type=str,
        choices=["hex", "int"],
        help="type generated",
        default="int",
    )
    args = parser.parse_args()

    if args.type == "int":
        generator = get_ints
    else:
        generator = get_hex
    print(",".join(map(str, generator())))


if __name__ == "__main__":
    main()
